services:
  - type: web
    name: my-django-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chatbot.wsgi:application

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

