# Generated by Django 5.2.3 on 2025-06-30 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_message_delete_previouschats"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inside_messages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bot.message"
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
