# Generated by Django 5.2.3 on 2025-06-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="name",
            field=models.CharField(default="New room", null=True),
        ),
    ]
