# Generated by Django 5.2.3 on 2025-06-30 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_rooms_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rooms",
            old_name="host",
            new_name="user",
        ),
    ]
