# Generated by Django 5.2.3 on 2025-06-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_rename_host_rooms_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rooms",
            old_name="user",
            new_name="host",
        ),
        migrations.RemoveField(
            model_name="rooms",
            name="inside_messages",
        ),
    ]
