# Generated by Django 5.2.3 on 2025-06-30 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_rename_user_rooms_host_remove_rooms_inside_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="bot.rooms"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.CharField(max_length=10),
        ),
    ]
